name: dotnet package

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release

      - name: Test with the dotnet CLI
        run: dotnet test

      - name: Publish
        run: dotnet publish -c Release

      - name: Build image
        run: docker build . --file Dockerfile --tag kataviv

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Push image
        run: |
          docker tag kataviv ghcr.io/rchoffardet/kataviv:latest
          docker push ghcr.io/rchoffardet/kataviv:latest
